[tool.bumpversion]
current_version = "1.2.5"
commit = true
tag = true
message = "v{new_version}"

[[tool.bumpversion.files]]
filename = "setup.py"

[[tool.bumpversion.files]]
filename = "scraper/__init__.py"
