name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: pip

      - name: Install package
        run: pip install -e .

      - name: Lint
        uses: pre-commit/action@v3.0.1

      - name: Test Project
        run: bash scripts/test.sh
